#!/usr/bin/env python3
"""Rebuild the conceptual CAD and electrical artifacts using only Python stdlib."""
from pathlib import Path
import argparse
import hashlib
import json
import math
import re
import shutil
import uuid
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent

def uid(name):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, 'solar-slingshot/' + name))

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--magnos', type=Path, default=Path('/Users/cybertwip/Downloads/Magnos'))
    args = parser.parse_args()
    beta = ROOT / 'reference/magnos-beta-5.0-alpha.kicad_sch'
    shutil.copyfile(beta, ROOT / 'magnos_beta_booster.kicad_sch')
    kicad = shutil.which('kicad-cli') or '/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli'
    subprocess.run([kicad, 'sch', 'export', 'netlist', '--format', 'kicadxml', str(beta), '-o', str(ROOT / 'magnos_beta_booster.xml')], check=True, capture_output=True)
    netlist = ET.parse(ROOT / 'magnos_beta_booster.xml').getroot()
    source_data = {
        'source': str(beta.relative_to(ROOT)), 'sha256': hashlib.sha256(beta.read_bytes()).hexdigest(),
        'components': [{'reference': c.get('ref'), 'value': c.findtext('value')} for c in netlist.findall('./components/comp')],
        'nets': [{'name': n.get('name'), 'pins': [f"{p.get('ref')}.{p.get('pin')}" for p in n.findall('node')]} for n in netlist.findall('./nets/net')],
        'annotations_not_verified_ratings': {'input_v': 5, 'input_a': 1, 'output_ac_v': 30000, 'output_ac_a': 0.087},
        'behavioral_assumptions': {'efficiency': 0.8, 'default_gain': 1, 'default_load_ohm': 1e9},
    }
    (ROOT / 'magnos_beta_connectivity.json').write_text(json.dumps(source_data, indent=2) + '\n')
    (ROOT / 'magnos_booster_equivalent.cir').write_text("""Magnos beta ideal power-limited envelope (not a switching model)
* Source connectivity in magnos_beta_booster.xml; gain/efficiency assumed.
.param gain=1 eta=0.8 imax=1 rload=1e9
VINPUT IN 0 5
BINPUT IN 0 I=V(OUT)*V(OUT)/({rload}*{eta}*max(V(IN),1e-12))
BOUTPUT OUT 0 V=min({gain}*V(IN),sqrt({eta}*max(V(IN),0)*{imax}*{rload}))
RLOAD OUT 0 {rload}
.op
.end
""")
    (ROOT / 'magnos_beta_board.scad').write_text("""// Board outline from beta PCB Edge.Cuts (70,15) to (160,125).
// Board thickness 1.6 mm from PCB general. Housing dimensions assumed.
module magnos_beta_board() { color("green") cube([90,110,1.6]); }
module magnos_beta_enclosure() {
  color("darkslategray") difference() {
    cube([110,130,60]);
    translate([3,3,3]) cube([104,124,60]);
  }
  translate([10,10,10]) magnos_beta_board();
}
if(is_undef(assembly_include)) magnos_beta_enclosure();
""")
    app = (ROOT / 'app.js').read_text()
    def constant(name):
        return float(re.search(rf'const {name} = ([\d_.]+);', app)[1].replace('_', ''))
    area = constant('SHIELD_AREA_M2')
    length = constant('COIL_LENGTH_M')
    turns = constant('COIL_TURNS')
    resistance = constant('COIL_RESISTANCE_OHM')
    inductance = constant('COIL_INDUCTANCE_H')
    current = constant('COIL_FIELD_LIMIT_T') * length / (4 * math.pi * 1e-7 * turns)
    source_manifest = {}
    for source, destination in [('schem.kicad_sch', 'magnos_reference.kicad_sch')]:
        data = (args.magnos / source).read_bytes()
        (ROOT / destination).write_bytes(data)
        source_manifest[source] = {'copy': destination, 'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data)}
    (ROOT / 'plasma_design_parameters.json').write_text(json.dumps({
        'source_directory': str(args.magnos), 'sources': source_manifest,
        'shield_area_m2': area, 'shield_radius_m': math.sqrt(area/math.pi),
        'coil_length_m': length, 'coil_turns': turns, 'coil_resistance_ohm': resistance,
        'coil_inductance_h': inductance, 'coil_limit_a': current,
        'coil_hold_voltage_v': current*resistance, 'coil_loss_w': current**2*resistance,
        'coil_stored_energy_j': .5*inductance*current**2,
        'geometry_status': 'Conceptual: only shield area, sheath thickness, coil length and turn count come from app.js. Other dimensions are assumed.'
    }, indent=2) + '\n')
    scad = f'''// Generated by generate_plasma_design.py. Dimensions in millimetres.
// Concept assembly, not a qualified pressure vessel, winding or plasma design.
// Magnos beta board outline comes from reference PCB; housing is assumed.
use <magnos_beta_board.scad>
$fn = 96;
model_scale = 1; // use 0.01 for a 1:100 display model
part = "assembly"; // assembly, shield, propulsion, magnos
cutaway = false;
shield_r = {math.sqrt(area/math.pi)*1000:.6f}; // app.js SHIELD_AREA_M2
sheath_t = {constant('SHIELD_SHEATH_THICKNESS_M')*1000};
coil_length = {length*1000};
coil_turns = {int(turns)};
module ring(ro, ri, h) {{ difference() {{ cylinder(r=ro,h=h); translate([0,0,-1]) cylinder(r=ri,h=h+2); }} }}
module shield() {{
  color("dimgray") cylinder(r=shield_r,h=120);
  color([0.72,0.45,0.20]) translate([0,0,-180]) ring(shield_r,shield_r-160,150);
  // Assumed annular injection manifold, with 24 indicated ports.
  color("silver") translate([0,0,120]) ring(shield_r-200,shield_r-280,80);
  for(a=[0:15:345]) rotate([0,0,a]) translate([shield_r-240,0,200])
    color("steelblue") cylinder(r=25,h=100);
  // Transparent sheath is a visualization, not a manufactured solid.
  %color([0.1,0.65,1,0.2]) translate([0,0,300]) cylinder(r=shield_r,h=sheath_t);
}}
module propulsion() {{
  // Assumed chamber bore 1.5 m; wall 80 mm; winding spacing schematic.
  color("silver") ring(830,750,coil_length);
  for(i=[0:coil_turns-1]) translate([0,0,i*coil_length/coil_turns])
    color([0.72,0.45,0.20]) ring(950,850,coil_length/coil_turns*0.65);
  color("dimgray") translate([0,0,-1500]) difference() {{
    cylinder(r1=1800,r2=830,h=1500);
    translate([0,0,-1]) cylinder(r1=1680,r2=750,h=1502);
  }}
  // Gas-feed manifold and neutralizer are conceptual geometry only.
  color("steelblue") translate([0,0,coil_length]) ring(950,750,150);
  color("gold") translate([1900,0,-1200]) cylinder(r=90,h=450);
}}
module magnos() {{ magnos_beta_enclosure(); }}
module assembly() {{
  translate([0,0,6000]) shield();
  translate([0,0,-coil_length]) propulsion();
  color("gray") ring(1250,1100,5700);
  translate([1300,0,2000]) magnos();
  // Folded radiator envelopes only: NOT the app's deployed radiator area.
  for(a=[0:90:270]) rotate([0,0,a]) translate([1300,-120,500])
    color("darkblue") cube([2500,240,4000]);
}}
scale(model_scale) difference() {{
  if(part=="shield") shield();
  else if(part=="propulsion") propulsion();
  else if(part=="magnos") magnos();
  else assembly();
  if(cutaway) translate([0,-20000,-10000]) cube([20000,40000,30000]);
}}
'''
    (ROOT / 'plasma_shield_propulsion.scad').write_text(scad)
    # A connected, explicit equivalent circuit. Ideal source/load abstractions,
    # not guessed transistor power electronics extrapolated from Magnos.
    hold = current*resistance
    beam_r = 6.6e6/current
    # app.js conductivity ceiling, electrode gap and area, duty averaged.
    shield_r = constant('SHIELD_ELECTRODE_GAP_M')/(constant('SHIELD_MAX_CONDUCTIVITY_S_M')*area)
    shield_i = min(40000/shield_r, constant('SHIELD_MAX_ELECTRODE_CURRENT_A_M2')*area)
    equivalent_r = 40000/(shield_i*constant('SHIELD_DUTY_CYCLE'))
    components = [
        ('V1','V',f'{hold:.6f} V hold','COIL_P','0',45,65),
        ('R1','R',f'{resistance} ohm','COIL_P','COIL_L',85,65),
        ('L1','L',f'{inductance} H','COIL_L','0',125,65),
        ('V2','V','6.6 MV ideal','BEAM_P','0',45,110),
        ('R2','R',f'{beam_r:.6f} ohm equivalent','BEAM_P','0',85,110),
        ('V3','V','40 kV ideal','SHIELD_P','0',45,155),
        ('R3','R',f'{equivalent_r:.6f} ohm duty average','SHIELD_P','0',85,155),
    ]
    root_id = uid('schematic')
    effects = '(effects (font (size 1.27 1.27)))'
    libs=[]
    for kind in ['V','R','L']:
        shape = '(circle (center 0 0) (radius 2.54) (stroke (width 0) (type default)) (fill (type none)))' if kind=='V' else '(rectangle (start -2.54 2.54) (end 2.54 -2.54) (stroke (width 0) (type default)) (fill (type none)))'
        libs.append(f'''(symbol "Equivalent:{kind}" (pin_names (offset 0) hide) (in_bom yes) (on_board yes)
(property "Reference" "{kind}" (at 0 5.08 0) {effects})
(property "Value" "{kind}" (at 0 -5.08 0) {effects})
(symbol "{kind}_0_1" {shape})
(symbol "{kind}_1_1"
(pin passive line (at -5.08 0 0) (length 2.54) (name "1" {effects}) (number "1" {effects}))
(pin passive line (at 5.08 0 180) (length 2.54) (name "2" {effects}) (number "2" {effects}))))''')
    sch=[f'(kicad_sch (version 20250114) (generator "eeschema") (uuid {root_id}) (paper "A4") (lib_symbols {"".join(libs)})']
    for ref,kind,value,n1,n2,x,y in components:
        sch.append(f'''(symbol (lib_id "Equivalent:{kind}") (at {x} {y} 0) (unit 1) (in_bom yes) (on_board yes) (dnp no) (uuid {uid(ref)})
(property "Reference" "{ref}" (at {x} {y-7} 0) {effects})
(property "Value" "{value}" (at {x} {y+7} 0) {effects})
(pin "1" (uuid {uid(ref+'pin1')})) (pin "2" (uuid {uid(ref+'pin2')}))
(instances (project "plasma_equivalent" (path "/{root_id}" (reference "{ref}") (unit 1)))))''')
        for side,net in [(-1,n1),(1,n2)]:
            xa=x+side*5.08; xb=x+side*10.16
            sch.append(f'(wire (pts (xy {xa} {y}) (xy {xb} {y})) (stroke (width 0) (type default)) (uuid {uid(ref+str(side)+"wire")}))')
            sch.append(f'(label "{net}" (at {xb} {y} 0) {effects} (uuid {uid(ref+str(side)+"label")}))')
    for text,y in [('PLASMA SHIELD / PROPULSION - IDEAL ELECTRICAL EQUIVALENT',20),
                   ('Simulation only. Not a construction schematic or validated plasma model.',27),
                   ('V1: regulated coil HOLD supply. R1: winding loss. L1: stored magnetic energy.',40),
                   ('V2/R2: accelerator operating-point load; neutralizer/feed/PPU not resolved.',90),
                   ('V3/R3: capped electrode current, 10 percent duty average; no MHD solved.',135),
                   ('Magnos preserved separately in magnos_reference.kicad_sch; interface unverified.',183)]:
        sch.append(f'(text "{text}" (at 145 {y} 0) {effects} (uuid {uid(text)}))')
    (ROOT / 'plasma_equivalent.kicad_sch').write_text('\n'.join(sch)+')\n')
    (ROOT / 'plasma_equivalent.cir').write_text(f'''Plasma electrical operating-point equivalent -- not a hardware design
* Magnos source retained separately; no verified control interface available.
* Coil hold voltage, zero initial current: asymptote equals app's 20 T limit.
V1 COIL_P 0 DC {hold:.9g}
R1 COIL_P COIL_L {resistance}
L1 COIL_L 0 {inductance} IC=0
* Accelerator at 6.6 MV. R2 is an operating-point surrogate for plasma.
V2 BEAM_P 0 DC 6.6e6
R2 BEAM_P 0 {beam_r:.9g}
* Shield electrode capped at {shield_i:.0f} A on-state; 10% duty average.
* Does not include motional current, sheath dynamics or photon heat.
V3 SHIELD_P 0 DC 40000
R3 SHIELD_P 0 {equivalent_r:.9g}
.op
.save v(COIL_L) i(L1)
.tran 100 100000 uic
.end
''')
    print('Generated SCAD, KiCad equivalent, SPICE, parameters and Magnos reference copy.')

if __name__ == '__main__':
    main()
