// Standalone generated assembly and harness. No external SCAD dependencies.
// Board outline from beta PCB Edge.Cuts (70,15) to (160,125).
// Board thickness 1.6 mm from PCB general. Housing dimensions assumed.
module magnos_beta_board() { color("green") cube([90,110,1.6]); }
module magnos_beta_enclosure() {
  color("darkslategray") difference() {
    cube([110,130,60]);
    translate([3,3,3]) cube([104,124,60]);
  }
  translate([10,10,10]) magnos_beta_board();
}

// Generated by generate_plasma_design.py. Dimensions in millimetres.
// Concept assembly, not a qualified pressure vessel, winding or plasma design.
// Magnos beta board outline comes from reference PCB; housing is assumed.

$fn = 96;
model_scale = 1; // use 0.01 for a 1:100 display model
part = "assembly"; // assembly, shield, propulsion, magnos
cutaway = false;
shield_r = 7569.397566; // app.js SHIELD_AREA_M2
sheath_t = 50.0;
coil_length = 2500.0;
coil_turns = 180;
module ring(ro, ri, h) { difference() { cylinder(r=ro,h=h); translate([0,0,-1]) cylinder(r=ri,h=h+2); } }
module shield() {
  color("dimgray") cylinder(r=shield_r,h=120);
  color([0.72,0.45,0.20]) translate([0,0,-180]) ring(shield_r,shield_r-160,150);
  // Assumed annular injection manifold, with 24 indicated ports.
  color("silver") translate([0,0,120]) ring(shield_r-200,shield_r-280,80);
  for(a=[0:15:345]) rotate([0,0,a]) translate([shield_r-240,0,200])
    color("steelblue") cylinder(r=25,h=100);
  // Transparent sheath is a visualization, not a manufactured solid.
  %color([0.1,0.65,1,0.2]) translate([0,0,300]) cylinder(r=shield_r,h=sheath_t);
}
module propulsion() {
  // Assumed chamber bore 1.5 m; wall 80 mm; winding spacing schematic.
  color("silver") ring(830,750,coil_length);
  for(i=[0:coil_turns-1]) translate([0,0,i*coil_length/coil_turns])
    color([0.72,0.45,0.20]) ring(950,850,coil_length/coil_turns*0.65);
  color("dimgray") translate([0,0,-1500]) difference() {
    cylinder(r1=1800,r2=830,h=1500);
    translate([0,0,-1]) cylinder(r1=1680,r2=750,h=1502);
  }
  // Gas-feed manifold and neutralizer are conceptual geometry only.
  color("steelblue") translate([0,0,coil_length]) ring(950,750,150);
  color("gold") translate([1900,0,-1200]) cylinder(r=90,h=450);
}
module magnos() { magnos_beta_enclosure(); }
module assembly() {
  translate([0,0,6000]) shield();
  translate([0,0,-coil_length]) propulsion();
  color("gray") ring(1250,1100,5700);
  translate([1300,0,2000]) magnos();
  // Folded radiator envelopes only: NOT the app's deployed radiator area.
  for(a=[0:90:270]) rotate([0,0,a]) translate([1300,-120,500])
    color("darkblue") cube([2500,240,4000]);
}
scale(model_scale) difference() {
  if(part=="shield") shield();
  else if(part=="propulsion") propulsion();
  else if(part=="magnos") magnos();
  else assembly();
  if(cutaway) translate([0,-20000,-10000]) cube([20000,40000,30000]);
}

// Generated functional cable routing, millimetres. NOT insulation/ampacity routing.
// Cable diameter exaggerated to 36 mm for full-vehicle visibility.
// Control/return bundles carry additional pins per magnos-plasma-wiring.json.
module cable(points,r=18) { for(i=[0:len(points)-2]) hull() {
 translate(points[i]) sphere(r=r,$fn=12);
 translate(points[i+1]) sphere(r=r,$fn=12);
} }
// SH_COIL_P
scale(model_scale) color([0.9, 0.3, 0.1]) cable([[1310, 0, 2020], [1400, 0, 2500], [1400, 0, 5700], [7300, 0, 5900]]);
// SH_COIL_N
scale(model_scale) color([0.1, 0.1, 0.2]) cable([[1320, 20, 2020], [1450, 50, 2500], [1450, 50, 5700], [7300, 100, 5900]]);
// SH_ELECTRODE_P
scale(model_scale) color([1, 0.6, 0]) cable([[1340, 40, 2020], [1600, 150, 2500], [1600, 150, 6250], [7200, 150, 6250]]);
// SH_ELECTRODE_N
scale(model_scale) color([0.5, 0.2, 0.8]) cable([[1350, 60, 2020], [1650, 220, 2500], [1650, 220, 6250], [7150, 220, 6250]]);
// PR_COIL_P
scale(model_scale) color([0.9, 0.3, 0.1]) cable([[1310, 0, 2010], [1400, -100, 500], [980, -100, -1200]]);
// PR_COIL_N
scale(model_scale) color([0.1, 0.1, 0.2]) cable([[1320, 20, 2010], [1450, -50, 500], [980, -50, -1250]]);
// PR_ELECTRODE_P
scale(model_scale) color([1, 0.6, 0]) cable([[1340, 40, 2010], [1600, 150, 0], [700, 150, -2400]]);
// PR_ELECTRODE_N
scale(model_scale) color([0.5, 0.2, 0.8]) cable([[1350, 60, 2010], [1650, 220, 0], [700, 220, -2500]]);
// NEUT_P
scale(model_scale) color([1, 0.6, 0]) cable([[1350, 80, 2010], [1900, 300, 0], [1900, 0, -3500]]);
// NEUT_N
scale(model_scale) color([0.5, 0.2, 0.8]) cable([[1360, 90, 2010], [1950, 350, 0], [1950, 0, -3500]]);
// SH_TEMP
scale(model_scale) color([0.2, 0.8, 0.4]) cable([[1360, 100, 2020], [1700, 350, 2500], [1700, 350, 6000], [7000, 350, 6000]]);
// PR_TEMP
scale(model_scale) color([0.2, 0.8, 0.4]) cable([[1370, 110, 2010], [1700, 350, 0], [1000, 350, -1200]]);
// GAS_P
scale(model_scale) color([0.2, 0.5, 1]) cable([[1380, 120, 2010], [1800, 500, 1000], [950, 500, 0]]);
// GAS_N
scale(model_scale) color([0.1, 0.2, 0.5]) cable([[1390, 130, 2010], [1850, 550, 1000], [950, 550, 0]]);
