// Generated by generate_plasma_design.py. Dimensions in millimetres.
// Concept assembly, not a qualified pressure vessel, winding or plasma design.
// Magnos beta board outline comes from reference PCB; housing is assumed.
use <magnos_beta_board.scad>
$fn = 96;
model_scale = 1; // use 0.01 for a 1:100 display model
part = "assembly"; // assembly, shield, propulsion, magnos
cutaway = false;
shield_r = 7569.397566; // app.js SHIELD_AREA_M2
sheath_t = 50.0;
coil_length = 2500.0;
coil_turns = 180;
module ring(ro, ri, h) { difference() { cylinder(r=ro,h=h); translate([0,0,-1]) cylinder(r=ri,h=h+2); } }
module shield() {
  color("dimgray") cylinder(r=shield_r,h=120);
  color([0.72,0.45,0.20]) translate([0,0,-180]) ring(shield_r,shield_r-160,150);
  // Assumed annular injection manifold, with 24 indicated ports.
  color("silver") translate([0,0,120]) ring(shield_r-200,shield_r-280,80);
  for(a=[0:15:345]) rotate([0,0,a]) translate([shield_r-240,0,200])
    color("steelblue") cylinder(r=25,h=100);
  // Transparent sheath is a visualization, not a manufactured solid.
  %color([0.1,0.65,1,0.2]) translate([0,0,300]) cylinder(r=shield_r,h=sheath_t);
}
module propulsion() {
  // Assumed chamber bore 1.5 m; wall 80 mm; winding spacing schematic.
  color("silver") ring(830,750,coil_length);
  for(i=[0:coil_turns-1]) translate([0,0,i*coil_length/coil_turns])
    color([0.72,0.45,0.20]) ring(950,850,coil_length/coil_turns*0.65);
  color("dimgray") translate([0,0,-1500]) difference() {
    cylinder(r1=1800,r2=830,h=1500);
    translate([0,0,-1]) cylinder(r1=1680,r2=750,h=1502);
  }
  // Gas-feed manifold and neutralizer are conceptual geometry only.
  color("steelblue") translate([0,0,coil_length]) ring(950,750,150);
  color("gold") translate([1900,0,-1200]) cylinder(r=90,h=450);
}
module magnos() { magnos_beta_enclosure(); }
module assembly() {
  translate([0,0,6000]) shield();
  translate([0,0,-coil_length]) propulsion();
  color("gray") ring(1250,1100,5700);
  translate([1300,0,2000]) magnos();
  // Folded radiator envelopes only: NOT the app's deployed radiator area.
  for(a=[0:90:270]) rotate([0,0,a]) translate([1300,-120,500])
    color("darkblue") cube([2500,240,4000]);
}
scale(model_scale) difference() {
  if(part=="shield") shield();
  else if(part=="propulsion") propulsion();
  else if(part=="magnos") magnos();
  else assembly();
  if(cutaway) translate([0,-20000,-10000]) cube([20000,40000,30000]);
}
